### ISSUE TITLE
Need  your help

### ISSUE THREAD

**Issue by kotanaavatharam** [DeveshRx/Android-WebRTC-Firebase#1]
I just cloned the webrtc from your repo. Thanks for the code.  

My Problem : It is working only when both devices are on the same network. If devices connected to different networks it is not working. Please help on this.

**Comment by DeveshRx** [comment]
I tested it on different network & it worked fine.
i think your network might have firewall or something which is causing issue.

try using TURN server, it might help

**Comment by ghost** [comment]
If you want to use WebRTC on different networks, you have to add TURN server.

**Comment by DeveshRx** [comment]
Use TURN servers fromTwilio to solve this issue :) 
https://www.twilio.com/stun-turn

or you can use your own TURN server if you have enough network bandwidth.
